//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.uiu
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Kat.
    /// </summary>
    //  *** Start programmer edit section *** (Kat CustomAttributes)

    //  *** End programmer edit section *** (Kat CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("KatE", new string[0])]
    [View("KatL", new string[0])]
    public class Kat : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (Kat CustomMembers)

        //  *** End programmer edit section *** (Kat CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "KatE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View KatE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("KatE", typeof(IIS.uiu.Kat));
                }
            }
            
            /// <summary>
            /// "KatL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View KatL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("KatL", typeof(IIS.uiu.Kat));
                }
            }
        }
    }
}
